name: flutter_mebel_app_rev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_database: ^10.3.1
  firebase_ui_database: ^1.3.11
  firebase_core: ^2.19.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  form_builder_image_picker: ^4.0.0
  cloud_firestore: ^4.11.0
  firebase_messaging: ^14.7.1
  get_secure_storage: ^1.0.4
  flutter_local_notifications: ^16.1.0
  url_launcher: ^6.1.14
  firebase_storage: ^11.3.1
  intl: ^0.18.1
  # flutter_localizations: 
  #   sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
  # generate: true

