// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOlrhLSQTL8hGTnXYQLjWpMwodwVXwzk',
    appId: '1:47854566464:web:a307d2a7008b89a602f3a5',
    messagingSenderId: '47854566464',
    projectId: 'flutter-mebel',
    authDomain: 'flutter-mebel.firebaseapp.com',
    storageBucket: 'flutter-mebel.appspot.com',
    measurementId: 'G-8QEWM75YBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5cICBq6C_R-gMFMXu04HkqMfcjtTz_Hw',
    appId: '1:47854566464:android:893f75244f81030902f3a5',
    messagingSenderId: '47854566464',
    projectId: 'flutter-mebel',
    storageBucket: 'flutter-mebel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYuRg7-YcxT6pAP74EE-0l6oqeJ5sbv4',
    appId: '1:47854566464:ios:91c2fb1a28027f0702f3a5',
    messagingSenderId: '47854566464',
    projectId: 'flutter-mebel',
    storageBucket: 'flutter-mebel.appspot.com',
    iosBundleId: 'com.example.flutterMebelAppRev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRYuRg7-YcxT6pAP74EE-0l6oqeJ5sbv4',
    appId: '1:47854566464:ios:c702b11b30c9164e02f3a5',
    messagingSenderId: '47854566464',
    projectId: 'flutter-mebel',
    storageBucket: 'flutter-mebel.appspot.com',
    iosBundleId: 'com.example.flutterMebelAppRev.RunnerTests',
  );
}
